2016-06-02 06:29:49,676 [MainThread:140269641873216] [dhui_init_product_data_command:handle:38] [ERROR]  - 错误信息：[Errno 111] Connection refused.
2016-06-02 06:29:50,676 [MainThread:139733188609856] [dhui_init_product_data_command:handle:38] [ERROR]  - 错误信息：[Errno 111] Connection refused.
2016-06-02 06:29:50,696 [MainThread:140150778836800] [dhui_init_product_data_command:handle:38] [ERROR]  - 错误信息：[Errno 111] Connection refused.
2016-06-02 06:29:50,696 [MainThread:139834291087168] [dhui_init_product_data_command:handle:38] [ERROR]  - 错误信息：[Errno 111] Connection refused.
2016-06-02 06:31:01,975 [MainThread:139868675331904] [dhui_init_product_data_command:handle:38] [ERROR]  - 错误信息：[Errno 111] Connection refused.
2016-06-03 01:53:24,065 [MainThread:140415406188352] [dhui_init_product_data_command:handle:38] [ERROR]  - 错误信息：<Fault invalid input syntax for integer: "571dbf0c006f874b52b126aa"
LINE 1: ...nfo" SET "product_tmpl_id"=3,"min_qty"=1.0,"name"='571dbf0c0...
                                                             ^
: 'Traceback (most recent call last):\n  File "/opt/odoo/openerp/service/wsgi_server.py", line 75, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/opt/odoo/openerp/http.py", line 115, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/odoo/openerp/service/model.py", line 37, in dispatch\n    res = fn(db, uid, *params)\n  File "/opt/odoo/openerp/service/model.py", line 167, in execute_kw\n    return execute(db, uid, obj, method, *args, **kw or {})\n  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper\n    return f(dbname, *args, **kwargs)\n  File "/opt/odoo/openerp/service/model.py", line 175, in execute\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\n  File "/opt/odoo/openerp/service/model.py", line 164, in execute_cr\n    return getattr(object, method)(cr, uid, *args, **kw)\n  File "/opt/odoo/openerp/api.py", line 268, in wrapper\n    return old_api(self, *args, **kwargs)\n  File "/opt/odoo/openerp/api.py", line 399, in old_api\n    result = method(recs, *args, **kwargs)\n  File "/opt/odoo/openerp/models.py", line 3788, in write\n    self._write(old_vals)\n  File "/opt/odoo/openerp/api.py", line 266, in wrapper\n    return new_api(self, *args, **kwargs)\n  File "/opt/odoo/openerp/api.py", line 592, in new_api\n    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)\n  File "/opt/odoo/openerp/models.py", line 3899, in _write\n    cr.execute(query, params + (sub_ids,))\n  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper\n    return f(self, *args, **kwargs)\n  File "/opt/odoo/openerp/sql_db.py", line 234, in execute\n    res = self._obj.execute(query, params)\nDataError: invalid input syntax for integer: "571dbf0c006f874b52b126aa"\nLINE 1: ...nfo" SET "product_tmpl_id"=3,"min_qty"=1.0,"name"=\'571dbf0c0...\n                                                             ^\n\n'>.
